config/routes.rb
Brianpetro::Application.routes.draw do
  get "contact" => 'contact#new', as: 'contact'
  post "contact" => 'contact#create', as: 'contact'
  resources :resources

  resources :dones

  resources :commits

  resources :entries

  get 'qscores/upvote/:id' => 'qscores#upvote'

	root to: 'entries#index'

end

app/models/commit.rb
class Commit < ActiveRecord::Base
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_action :set_commit, only: [:show, :edit, :update, :destroy]

  # GET /commits
  # GET /commits.json
  def index
    @commits = Commit.all
  end

  # GET /commits/1
  # GET /commits/1.json
  def show
  end

  # GET /commits/new
  def new
    @commit = Commit.new
  end

  # GET /commits/1/edit
  def edit
  end

  # POST /commits
  # POST /commits.json
  def create
    @commit = Commit.new(commit_params)

    respond_to do |format|
      if @commit.save
        format.html { redirect_to @commit, notice: 'Commit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @commit }
      else
        format.html { render action: 'new' }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commits/1
  # PATCH/PUT /commits/1.json
  def update
    respond_to do |format|
      if @commit.update(commit_params)
        format.html { redirect_to @commit, notice: 'Commit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commits/1
  # DELETE /commits/1.json
  def destroy
    @commit.destroy
    respond_to do |format|
      format.html { redirect_to commits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commit
      @commit = Commit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commit_params
      params.require(:commit).permit(:commit, :repo, :commit_timestamp)
    end
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/views/commits/_form.html.erb
<%= form_for(@commit) do |f| %>
  <% if @commit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit.errors.count, "error") %> prohibited this commit from being saved:</h2>

      <ul>
      <% @commit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commit %><br />
    <%= f.text_area :commit %>
  </div>
  <div class="field">
    <%= f.label :repo %><br />
    <%= f.text_field :repo %>
  </div>
  <div class="field">
    <%= f.label :commit_timestamp %><br />
    <%= f.text_field :commit_timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commits/edit.html.erb
<h1>Editing commit</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit %> |
<%= link_to 'Back', commits_path %>

app/views/commits/index.html.erb
<h1>Listing commits</h1>

<table>
  <thead>
    <tr>
      <th>Commit</th>
      <th>Repo</th>
      <th>Commit timestamp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commits.each do |commit| %>
    <tr>
      <td><%= commit.commit %></td>
      <td><%= commit.repo %></td>
      <td><%= commit.commit_timestamp %></td>
      <td><%= link_to 'Show', commit %></td>
      <td><%= link_to 'Edit', edit_commit_path(commit) %></td>
      <td><%= link_to 'Destroy', commit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Commit', new_commit_path %>

app/views/commits/new.html.erb
<h1>New commit</h1>

<%= render 'form' %>

<%= link_to 'Back', commits_path %>

app/views/commits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commit:</strong>
  <%= @commit.commit %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @commit.repo %>
</p>

<p>
  <strong>Commit timestamp:</strong>
  <%= @commit.commit_timestamp %>
</p>

<%= link_to 'Edit', edit_commit_path(@commit) %> |
<%= link_to 'Back', commits_path %>