config/routes.rb
Brianpetro::Application.routes.draw do
  get "contact" => 'contact#new', as: 'contact'
  post "contact" => 'contact#create', as: 'contact'
  resources :resources

  resources :dones

  resources :commits

  resources :entries

  get 'qscores/upvote/:id' => 'qscores#upvote'

	root to: 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
	respond_to :json, :html, :pdf

  # GET /entries
  def index
  	@entries = Entry.order('title').each
  	respond_to do |format|
    	format.json do
    		render json: @entries.as_json
    	end
    	format.html do
    		respond_with @entries
    	end
    	format.pdf do
    		pdf = ResumePdf.new(@entries)
    		send_data pdf.render, filename: "Brian_Petro_Resume_#{Time.now}",
    													type: "application/pdf",
    													disposition: "inline"
    	end
    end
  end

  # GET /entries/1
  def show
  end

  # GET /entries/new
  def new
  	if params[:unlock]
    	@entry = Entry.new
   	else
   		redirect_to root_path
   	end
  end

  # GET /entries/1/edit
  def edit
    if params[:unlock]

   	else
   		redirect_to root_path
   	end
  end

  # POST /entries
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to root_path, notice: 'Entry was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /entries/1
  def update
    if @entry.update(entry_params)
      redirect_to root_path, notice: 'Entry was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    redirect_to entries_url, notice: 'Entry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def entry_params
      params.require(:entry).permit(:title, :details, :entry_url, :tech)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<head>
	<script type="text/javascript">
	tinyMCE.init({
		document_base_url : "http://www.tanveerhuq.com/",
		mode : "textareas"
	});
	</script>
</head>

<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %><br>
  </div>
  <div class="field">
    <%= f.label :entry_url %>
    <%= f.text_field :entry_url %><br>
  </div>
  <div class="field">
    <%= f.label :tech %>
    <%= f.check_box :tech %><br>
  </div>
  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div class="row-fluid">
	<div class="span8 offset2 alert alert-danger">
		<h2>Under construction. <a href="http://www.linkedin.com/profile/view?id=63338678">Connect</a> with me to learn more.</h2>
	</div>
</div>
<div ng-controller="EntryCtrl">
	<div class="row-fluid">
		<div class="span5 offset1">
			<div class="">
				<h1>Hi. I'm Tanveer.</h1>
				<hr>
				<!-- Linkedin -->
				<a href="http://www.linkedin.com/profile/view?id=63338678" class="btn btn-primary">
					<img src="https://s1-s.licdn.com/scds/common/u/img/logos/LinkedIn_logo_white_92x22_v2.png"alt="View Tanveer Huq's profile on LinkedIn"></a>
				<a href="/entries.pdf" class="btn btn-danger"><strong>View Resume PDF</strong></a>
				<!-- StackOverflow -->
			</div>
		</div>
	</div>
	<hr>
	<div class="row-fluid">
		<div class="offset1">
			<h2>Hire me so you can...</h2>
		</div>
		<div class="offset2">
			<h3>Launch your software as a service(saas) business.</h3>
		</div>
		<div class="offset2">
			<h3>Have an extra hand on your current project.</h3>
		</div>
		<div class="offset2">
			<h3>Save time with automation.</h3>
		</div>
		<div class="offset2">
			<h3>Close github issues.</h3>
		</div>
	</div>
	<hr>
	<div class="row-fluid">
		<div class="offset1">
			<h2>Let's begin.</h2>
		</div>
		<div class="offset2">
			<ul class="unstyled">
				<li>
					<h3>Discovery</h3>
					<p>We begin with an initial consultation. Tell me the story behind your project.</p>
				</li>
				<li>
					<h3>Determine needs and budget.</h3>
				</li>
				<li>
					<h3>Receive a proposal.</h3>
				</li>
				<li>
					<h3>Agree on timeframes, deliverables, and requirements.</h3>
				</li>
				<li>
					<h3>Development and communication.</h3>
				</li>
			</ul>
		</div>
	</div>
	<hr>
	<div class="row-fluid">
		<div class="offset1">
			<h2>Click to explore my history.</h2>
		</div>
		<div class="span8 offset2">
			<entry-list></entry-list>
		</div> <!-- class span -->
	</div> <!-- class row -->
	<hr>
	<div class="row-fluid">
		<div class="offset1">
			<h2>Send me an email.</h2>
		</div>
		<div class="offset2 span4">
			<form accept-charset="UTF-8" action="/contact" class="message" data-post-form="new_message" id="contact" method="post">
				<div style="margin:0;padding:0;display:inline">
					<input name="utf8" type="hidden" value="&#x2713;" />
					<input name="_method" type="hidden" value="post" />
					<input name="authenticity_token" type="hidden" value="{{$httpProvider.defaults.headers.common['X-CSRF-Token']}}" />
				</div>
				<div class="field">
				  <label for="message_email">Your Email:</label>
				  <input required id="message_email" class="input-block-level" name="message[email]" type="text" />
				</div>
				<div class="field">
					<label for="message_body">Your Message:</label>
					<textarea required id="message_body" style="height:8em;" class="input-block-level" name="message[body]"></textarea>
				</div>
				<br><input name="commit" class="btn btn-success pull-right" type="submit" value="Send" />
			</form>
		</div>
	</div>
</div> <!-- ng-controller -->

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<ul>
	<% Octokit.list_commits("brianpetro/resume").each do |e| %>
		<li>
			<%= e.commit.message %>
		</li>
	<% end %>
</ul>