config/routes.rb
Brianpetro::Application.routes.draw do
  get "contact" => 'contact#new', as: 'contact'
  post "contact" => 'contact#create', as: 'contact'
  resources :resources

  resources :dones

  resources :commits

  resources :entries

  get 'qscores/upvote/:id' => 'qscores#upvote'

	root to: 'entries#index'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
		<%= f.label :tag_list, "Tags (separated by commas)" %><br />
		<%= f.text_field :tag_list %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<div ng-controller="ResourceCtrl">
	<h1>Resources</h1>
	<form ng-submit="addResource()" class="form-search">
		<input type="string" ng-model="newResource.url">
		<input type="submit" value="Add">
	</form>
	<span class="lead">Instant Search URL and Tags</span>
	<input type="text" ng-model="search.$" class="input-large search-query">
	<table class="table table-bordered">
		<tr ng-repeat="site in resources | filter:search">
			<td>
				<a href="/qscores/upvote/{{site.qscores[0].id}}" ng-show="site.qscores[0].id" class="btn btn-info">upvote</a>
				<a class="btn btn-success" href="{{site.site.url}}">Open Resource</a>
			</td>
			<td>
				<ul class="unstyled">
					<li>
						<span ng-repeat="tag in site.tags">
							{{tag.name}},
						</span>
					</li>
					<li>
						<a class="btn btn-mini" href="/resources/{{site.site.id}}/edit">Edit</a>
					</li>
				</ul>
			</td>
		</tr>
	</table>
</div>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>